<?php

declare(strict_types=1);

namespace App\Domain\Backoffice\Product\Requests;

use App\Infrastructure\Storage\Validations\FileValidationRules;
use Illuminate\Foundation\Http\FormRequest;

class ProductCreateRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'category_id' => ['required', 'uuid', 'exists:categories,id'],
            'name' => ['required', 'string', 'max:255'],
            'slug' => ['sometimes', 'string', 'max:255', 'unique:products,slug'],
            'description' => ['nullable', 'string', 'max:5000'],
            'price' => ['required', 'numeric', 'min:0', 'max:999999999.99'],
            'thumbnail_path' => ['required', 'string', 'max:500'],
            'images_paths' => ['required', 'array', 'max:10'],
            'images_paths.*' => ['string', 'max:500'],
            'stock' => ['required', 'integer', 'min:0'],
            // Note: status is NOT included - it's auto-generated by observer
        ];
    }
}
